include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - banxa
    - squidrouter
    - packages/genius_api/lib/proto

formatter:
  page_width: 80
