// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'wallet.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$WalletImpl _$$WalletImplFromJson(Map<String, dynamic> json) => _$WalletImpl(
      coinType: $enumDecode(_$TWCoinTypeEnumMap, json['coinType']),
      walletName: json['walletName'] as String,
      currencySymbol: json['currencySymbol'] as String,
      walletType: $enumDecode(_$WalletTypeEnumMap, json['walletType']),
      balance: (json['balance'] as num).toDouble(),
      address: json['address'] as String,
    );

Map<String, dynamic> _$$WalletImplToJson(_$WalletImpl instance) =>
    <String, dynamic>{
      'coinType': _$TWCoinTypeEnumMap[instance.coinType]!,
      'walletName': instance.walletName,
      'currencySymbol': instance.currencySymbol,
      'walletType': _$WalletTypeEnumMap[instance.walletType]!,
      'balance': instance.balance,
      'address': instance.address,
    };

const _$TWCoinTypeEnumMap = {
  TWCoinType.TWCoinTypeAeternity: 'TWCoinTypeAeternity',
  TWCoinType.TWCoinTypeAion: 'TWCoinTypeAion',
  TWCoinType.TWCoinTypeBinance: 'TWCoinTypeBinance',
  TWCoinType.TWCoinTypeBitcoin: 'TWCoinTypeBitcoin',
  TWCoinType.TWCoinTypeBitcoinCash: 'TWCoinTypeBitcoinCash',
  TWCoinType.TWCoinTypeBitcoinGold: 'TWCoinTypeBitcoinGold',
  TWCoinType.TWCoinTypeCallisto: 'TWCoinTypeCallisto',
  TWCoinType.TWCoinTypeCardano: 'TWCoinTypeCardano',
  TWCoinType.TWCoinTypeCosmos: 'TWCoinTypeCosmos',
  TWCoinType.TWCoinTypeDash: 'TWCoinTypeDash',
  TWCoinType.TWCoinTypeDecred: 'TWCoinTypeDecred',
  TWCoinType.TWCoinTypeDigiByte: 'TWCoinTypeDigiByte',
  TWCoinType.TWCoinTypeDogecoin: 'TWCoinTypeDogecoin',
  TWCoinType.TWCoinTypeEOS: 'TWCoinTypeEOS',
  TWCoinType.TWCoinTypeWAX: 'TWCoinTypeWAX',
  TWCoinType.TWCoinTypeEthereum: 'TWCoinTypeEthereum',
  TWCoinType.TWCoinTypeEthereumClassic: 'TWCoinTypeEthereumClassic',
  TWCoinType.TWCoinTypeFIO: 'TWCoinTypeFIO',
  TWCoinType.TWCoinTypeGoChain: 'TWCoinTypeGoChain',
  TWCoinType.TWCoinTypeGroestlcoin: 'TWCoinTypeGroestlcoin',
  TWCoinType.TWCoinTypeICON: 'TWCoinTypeICON',
  TWCoinType.TWCoinTypeIoTeX: 'TWCoinTypeIoTeX',
  TWCoinType.TWCoinTypeKava: 'TWCoinTypeKava',
  TWCoinType.TWCoinTypeKin: 'TWCoinTypeKin',
  TWCoinType.TWCoinTypeLitecoin: 'TWCoinTypeLitecoin',
  TWCoinType.TWCoinTypeMonacoin: 'TWCoinTypeMonacoin',
  TWCoinType.TWCoinTypeNebulas: 'TWCoinTypeNebulas',
  TWCoinType.TWCoinTypeNULS: 'TWCoinTypeNULS',
  TWCoinType.TWCoinTypeNano: 'TWCoinTypeNano',
  TWCoinType.TWCoinTypeNEAR: 'TWCoinTypeNEAR',
  TWCoinType.TWCoinTypeNimiq: 'TWCoinTypeNimiq',
  TWCoinType.TWCoinTypeOntology: 'TWCoinTypeOntology',
  TWCoinType.TWCoinTypePOANetwork: 'TWCoinTypePOANetwork',
  TWCoinType.TWCoinTypeQtum: 'TWCoinTypeQtum',
  TWCoinType.TWCoinTypeXRP: 'TWCoinTypeXRP',
  TWCoinType.TWCoinTypeSolana: 'TWCoinTypeSolana',
  TWCoinType.TWCoinTypeStellar: 'TWCoinTypeStellar',
  TWCoinType.TWCoinTypeTezos: 'TWCoinTypeTezos',
  TWCoinType.TWCoinTypeTheta: 'TWCoinTypeTheta',
  TWCoinType.TWCoinTypeThunderCore: 'TWCoinTypeThunderCore',
  TWCoinType.TWCoinTypeNEO: 'TWCoinTypeNEO',
  TWCoinType.TWCoinTypeTomoChain: 'TWCoinTypeTomoChain',
  TWCoinType.TWCoinTypeTron: 'TWCoinTypeTron',
  TWCoinType.TWCoinTypeVeChain: 'TWCoinTypeVeChain',
  TWCoinType.TWCoinTypeViacoin: 'TWCoinTypeViacoin',
  TWCoinType.TWCoinTypeWanchain: 'TWCoinTypeWanchain',
  TWCoinType.TWCoinTypeZcash: 'TWCoinTypeZcash',
  TWCoinType.TWCoinTypeFiro: 'TWCoinTypeFiro',
  TWCoinType.TWCoinTypeZilliqa: 'TWCoinTypeZilliqa',
  TWCoinType.TWCoinTypeZelcash: 'TWCoinTypeZelcash',
  TWCoinType.TWCoinTypeRavencoin: 'TWCoinTypeRavencoin',
  TWCoinType.TWCoinTypeWaves: 'TWCoinTypeWaves',
  TWCoinType.TWCoinTypeTerra: 'TWCoinTypeTerra',
  TWCoinType.TWCoinTypeTerraV2: 'TWCoinTypeTerraV2',
  TWCoinType.TWCoinTypeHarmony: 'TWCoinTypeHarmony',
  TWCoinType.TWCoinTypeAlgorand: 'TWCoinTypeAlgorand',
  TWCoinType.TWCoinTypeKusama: 'TWCoinTypeKusama',
  TWCoinType.TWCoinTypePolkadot: 'TWCoinTypePolkadot',
  TWCoinType.TWCoinTypeFilecoin: 'TWCoinTypeFilecoin',
  TWCoinType.TWCoinTypeMultiversX: 'TWCoinTypeMultiversX',
  TWCoinType.TWCoinTypeBandChain: 'TWCoinTypeBandChain',
  TWCoinType.TWCoinTypeSmartChainLegacy: 'TWCoinTypeSmartChainLegacy',
  TWCoinType.TWCoinTypeSmartChain: 'TWCoinTypeSmartChain',
  TWCoinType.TWCoinTypeOasis: 'TWCoinTypeOasis',
  TWCoinType.TWCoinTypePolygon: 'TWCoinTypePolygon',
  TWCoinType.TWCoinTypeTHORChain: 'TWCoinTypeTHORChain',
  TWCoinType.TWCoinTypeBluzelle: 'TWCoinTypeBluzelle',
  TWCoinType.TWCoinTypeOptimism: 'TWCoinTypeOptimism',
  TWCoinType.TWCoinTypeZksync: 'TWCoinTypeZksync',
  TWCoinType.TWCoinTypeArbitrum: 'TWCoinTypeArbitrum',
  TWCoinType.TWCoinTypeECOChain: 'TWCoinTypeECOChain',
  TWCoinType.TWCoinTypeAvalancheCChain: 'TWCoinTypeAvalancheCChain',
  TWCoinType.TWCoinTypeXDai: 'TWCoinTypeXDai',
  TWCoinType.TWCoinTypeFantom: 'TWCoinTypeFantom',
  TWCoinType.TWCoinTypeCryptoOrg: 'TWCoinTypeCryptoOrg',
  TWCoinType.TWCoinTypeCelo: 'TWCoinTypeCelo',
  TWCoinType.TWCoinTypeRonin: 'TWCoinTypeRonin',
  TWCoinType.TWCoinTypeOsmosis: 'TWCoinTypeOsmosis',
  TWCoinType.TWCoinTypeECash: 'TWCoinTypeECash',
  TWCoinType.TWCoinTypeCronosChain: 'TWCoinTypeCronosChain',
  TWCoinType.TWCoinTypeSmartBitcoinCash: 'TWCoinTypeSmartBitcoinCash',
  TWCoinType.TWCoinTypeKuCoinCommunityChain: 'TWCoinTypeKuCoinCommunityChain',
  TWCoinType.TWCoinTypeBoba: 'TWCoinTypeBoba',
  TWCoinType.TWCoinTypeMetis: 'TWCoinTypeMetis',
  TWCoinType.TWCoinTypeAurora: 'TWCoinTypeAurora',
  TWCoinType.TWCoinTypeEvmos: 'TWCoinTypeEvmos',
  TWCoinType.TWCoinTypeNativeEvmos: 'TWCoinTypeNativeEvmos',
  TWCoinType.TWCoinTypeMoonriver: 'TWCoinTypeMoonriver',
  TWCoinType.TWCoinTypeMoonbeam: 'TWCoinTypeMoonbeam',
  TWCoinType.TWCoinTypeKavaEvm: 'TWCoinTypeKavaEvm',
  TWCoinType.TWCoinTypeKlaytn: 'TWCoinTypeKlaytn',
  TWCoinType.TWCoinTypeMeter: 'TWCoinTypeMeter',
  TWCoinType.TWCoinTypeOKXChain: 'TWCoinTypeOKXChain',
  TWCoinType.TWCoinTypeNervos: 'TWCoinTypeNervos',
  TWCoinType.TWCoinTypeEverscale: 'TWCoinTypeEverscale',
  TWCoinType.TWCoinTypeAptos: 'TWCoinTypeAptos',
  TWCoinType.TWCoinTypeHedera: 'TWCoinTypeHedera',
  TWCoinType.TWCoinTypeSecret: 'TWCoinTypeSecret',
  TWCoinType.TWCoinTypeNativeInjective: 'TWCoinTypeNativeInjective',
  TWCoinType.TWCoinTypeAgoric: 'TWCoinTypeAgoric',
  TWCoinType.TWCoinTypeTON: 'TWCoinTypeTON',
  TWCoinType.TWCoinTypeSui: 'TWCoinTypeSui',
  TWCoinType.TWCoinTypeStargaze: 'TWCoinTypeStargaze',
  TWCoinType.TWCoinTypePolygonzkEVM: 'TWCoinTypePolygonzkEVM',
  TWCoinType.TWCoinTypeJuno: 'TWCoinTypeJuno',
  TWCoinType.TWCoinTypeStride: 'TWCoinTypeStride',
  TWCoinType.TWCoinTypeAxelar: 'TWCoinTypeAxelar',
  TWCoinType.TWCoinTypeCrescent: 'TWCoinTypeCrescent',
  TWCoinType.TWCoinTypeKujira: 'TWCoinTypeKujira',
  TWCoinType.TWCoinTypeIoTeXEVM: 'TWCoinTypeIoTeXEVM',
  TWCoinType.TWCoinTypeNativeCanto: 'TWCoinTypeNativeCanto',
  TWCoinType.TWCoinTypeComdex: 'TWCoinTypeComdex',
  TWCoinType.TWCoinTypeNeutron: 'TWCoinTypeNeutron',
  TWCoinType.TWCoinTypeSommelier: 'TWCoinTypeSommelier',
  TWCoinType.TWCoinTypeFetchAI: 'TWCoinTypeFetchAI',
  TWCoinType.TWCoinTypeMars: 'TWCoinTypeMars',
  TWCoinType.TWCoinTypeUmee: 'TWCoinTypeUmee',
  TWCoinType.TWCoinTypeCoreum: 'TWCoinTypeCoreum',
  TWCoinType.TWCoinTypeQuasar: 'TWCoinTypeQuasar',
  TWCoinType.TWCoinTypePersistence: 'TWCoinTypePersistence',
  TWCoinType.TWCoinTypeAkash: 'TWCoinTypeAkash',
  TWCoinType.TWCoinTypeNoble: 'TWCoinTypeNoble',
};

const _$WalletTypeEnumMap = {
  WalletType.tracking: 'tracking',
  WalletType.privateKey: 'privateKey',
  WalletType.mnemonic: 'mnemonic',
  WalletType.keystore: 'keystore',
  WalletType.sgnus: 'sgnus',
};
