// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// @brief Inits the SDK with saved settings (no private key - uses existing wallet).
  /// If no account exists, creates with a random mnemonic.
  /// @param[in] base_path  Base path for node data storage.
  /// @param[in] dev_config Developer configuration JSON string (Address, Cut, TokenValue, TokenID).
  /// @returns Initialization path in case of success, null on failure.
  ffi.Pointer<ffi.Char> GeniusSDKInit(
    ffi.Pointer<ffi.Char> base_path,
    ffi.Pointer<ffi.Char> dev_config,
  ) {
    return _GeniusSDKInit(base_path, dev_config);
  }

  late final _GeniusSDKInitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('GeniusSDKInit');
  late final _GeniusSDKInit =
      _GeniusSDKInitPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// @brief Inits the SDK with an ethereum private key.
  /// @param[in] base_path       Base path for node data storage.
  /// @param[in] dev_config      Developer configuration JSON string.
  /// @param[in] eth_private_key Valid HEX ethereum key, supports '0x' prefix.
  /// @returns Initialization path in case of success, null on failure.
  ffi.Pointer<ffi.Char> GeniusSDKInitWithKey(
    ffi.Pointer<ffi.Char> base_path,
    ffi.Pointer<ffi.Char> dev_config,
    ffi.Pointer<ffi.Char> eth_private_key,
  ) {
    return _GeniusSDKInitWithKey(base_path, dev_config, eth_private_key);
  }

  late final _GeniusSDKInitWithKeyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('GeniusSDKInitWithKey');
  late final _GeniusSDKInitWithKey =
      _GeniusSDKInitWithKeyPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// @brief Inits the SDK with a BIP39 mnemonic recovery phrase.
  /// @param[in] base_path  Base path for node data storage.
  /// @param[in] dev_config Developer configuration JSON string.
  /// @param[in] mnemonic   BIP39 mnemonic recovery phrase.
  /// @returns Initialization path in case of success, null on failure.
  ffi.Pointer<ffi.Char> GeniusSDKInitWithMnemonic(
    ffi.Pointer<ffi.Char> base_path,
    ffi.Pointer<ffi.Char> dev_config,
    ffi.Pointer<ffi.Char> mnemonic,
  ) {
    return _GeniusSDKInitWithMnemonic(base_path, dev_config, mnemonic);
  }

  late final _GeniusSDKInitWithMnemonicPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('GeniusSDKInitWithMnemonic');
  late final _GeniusSDKInitWithMnemonic =
      _GeniusSDKInitWithMnemonicPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// @brief Shuts down the SDK and releases all node resources.
  /// @returns @ref GENIUS_NODE_RET_OK on success.
  int GeniusSDKShutdown() {
    return _GeniusSDKShutdown();
  }

  late final _GeniusSDKShutdownPtr =
      _lookup<ffi.NativeFunction<GeniusNodeReturnValue_t Function()>>(
        'GeniusSDKShutdown',
      );
  late final _GeniusSDKShutdown =
      _GeniusSDKShutdownPtr.asFunction<int Function()>();

  /// @brief Reloads log level overrides from log_config.json at runtime.
  void GeniusSDKLoadLogConfig() {
    return _GeniusSDKLoadLogConfig();
  }

  late final _GeniusSDKLoadLogConfigPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
        'GeniusSDKLoadLogConfig',
      );
  late final _GeniusSDKLoadLogConfig =
      _GeniusSDKLoadLogConfigPtr.asFunction<void Function()>();

  /// @brief Frees memory allocated by the SDK.
  /// @param[in] ptr Pointer to the memory block to free. May be null (no-op).
  void GeniusSDKFree(ffi.Pointer<ffi.Void> ptr) {
    return _GeniusSDKFree(ptr);
  }

  late final _GeniusSDKFreePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'GeniusSDKFree',
      );
  late final _GeniusSDKFree =
      _GeniusSDKFreePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// @brief Retrieves the current SDK initialization progress.
  /// @return A @ref GeniusStatusInfo struct containing:
  /// - `percentage`: Initialization progress from 0.0 to 1.0
  /// - `message`: A null-terminated string describing the current initialization step,
  /// or null if the SDK is not initialized. The caller must free `message` with
  /// @ref GeniusSDKFree().
  GeniusStatusInfo GeniusSDKGetInitializationStatus() {
    return _GeniusSDKGetInitializationStatus();
  }

  late final _GeniusSDKGetInitializationStatusPtr =
      _lookup<ffi.NativeFunction<GeniusStatusInfo Function()>>(
        'GeniusSDKGetInitializationStatus',
      );
  late final _GeniusSDKGetInitializationStatus =
      _GeniusSDKGetInitializationStatusPtr.asFunction<
        GeniusStatusInfo Function()
      >();

  /// @brief Retrieves a list of available Genius accounts.
  /// @return A null-terminated string containing newline-separated hex addresses,
  /// or null if the SDK is not initialized. The caller must free the
  /// returned string with free().
  ffi.Pointer<ffi.Char> GeniusSDKGetAvailableAccounts() {
    return _GeniusSDKGetAvailableAccounts();
  }

  late final _GeniusSDKGetAvailableAccountsPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'GeniusSDKGetAvailableAccounts',
      );
  late final _GeniusSDKGetAvailableAccounts =
      _GeniusSDKGetAvailableAccountsPtr.asFunction<
        ffi.Pointer<ffi.Char> Function()
      >();

  /// @brief Adds a new account using an Ethereum private key.
  /// @param[in] private_key Null-terminated string representing the private key in hex format (0x prefix optional).
  /// @return @ref GENIUS_NODE_RET_OK on success, @ref GENIUS_NODE_ERROR_NOT_INITIALIZED if the SDK is not initialized,
  /// or @ref GENIUS_NODE_INVALID_ARGUMENT on failure.
  int GeniusSDKAddAccountWithPrivateKey(ffi.Pointer<ffi.Char> private_key) {
    return _GeniusSDKAddAccountWithPrivateKey(private_key);
  }

  late final _GeniusSDKAddAccountWithPrivateKeyPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(ffi.Pointer<ffi.Char>)
        >
      >('GeniusSDKAddAccountWithPrivateKey');
  late final _GeniusSDKAddAccountWithPrivateKey =
      _GeniusSDKAddAccountWithPrivateKeyPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// @brief Adds a new account using a mnemonic phrase.
  /// @param[in] mnemonic Null-terminated string representing the mnemonic recovery phrase.
  /// @return @ref GENIUS_NODE_RET_OK on success, @ref GENIUS_NODE_ERROR_NOT_INITIALIZED if the SDK is not initialized,
  /// or @ref GENIUS_NODE_INVALID_ARGUMENT on failure.
  int GeniusSDKAddAccountWithMnemonic(ffi.Pointer<ffi.Char> mnemonic) {
    return _GeniusSDKAddAccountWithMnemonic(mnemonic);
  }

  late final _GeniusSDKAddAccountWithMnemonicPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(ffi.Pointer<ffi.Char>)
        >
      >('GeniusSDKAddAccountWithMnemonic');
  late final _GeniusSDKAddAccountWithMnemonic =
      _GeniusSDKAddAccountWithMnemonicPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// @brief Adds a new account using a randomly generated mnemonic phrase.
  /// @return A @ref GeniusMnemonicAndStatus struct. On success, `status` is
  /// @ref GENIUS_NODE_RET_OK and `mnemonic` contains the generated phrase
  /// (must be freed with @ref GeniusSDKFree). On failure, `status` is
  /// @ref GENIUS_NODE_ERROR_NOT_INITIALIZED and `mnemonic` is null.
  GeniusMnemonicAndStatus GeniusSDKAddAccountWithRandomMnemonic() {
    return _GeniusSDKAddAccountWithRandomMnemonic();
  }

  late final _GeniusSDKAddAccountWithRandomMnemonicPtr =
      _lookup<ffi.NativeFunction<GeniusMnemonicAndStatus Function()>>(
        'GeniusSDKAddAccountWithRandomMnemonic',
      );
  late final _GeniusSDKAddAccountWithRandomMnemonic =
      _GeniusSDKAddAccountWithRandomMnemonicPtr.asFunction<
        GeniusMnemonicAndStatus Function()
      >();

  /// @brief Selects the active account for subsequent SDK operations.
  /// @param[in] public_address Null-terminated string representing the account's public address.
  /// @return @ref GENIUS_NODE_RET_OK on success, @ref GENIUS_NODE_ERROR_CREATING if not initialized,
  /// or @ref GENIUS_NODE_INVALID_ARGUMENT on failure.
  int GeniusSDKSelectGeniusAccount(ffi.Pointer<ffi.Char> public_address) {
    return _GeniusSDKSelectGeniusAccount(public_address);
  }

  late final _GeniusSDKSelectGeniusAccountPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(ffi.Pointer<ffi.Char>)
        >
      >('GeniusSDKSelectGeniusAccount');
  late final _GeniusSDKSelectGeniusAccount =
      _GeniusSDKSelectGeniusAccountPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// @brief Transfers an account to a different address.
  /// @param[in] public_address Null-terminated string representing the target public address.
  /// @return @ref GENIUS_NODE_RET_OK on success, @ref GENIUS_NODE_ERROR_CREATING if not initialized,
  /// or @ref GENIUS_NODE_INVALID_ARGUMENT on failure.
  int GeniusSDKTransferGeniusAccount(ffi.Pointer<ffi.Char> public_address) {
    return _GeniusSDKTransferGeniusAccount(public_address);
  }

  late final _GeniusSDKTransferGeniusAccountPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(ffi.Pointer<ffi.Char>)
        >
      >('GeniusSDKTransferGeniusAccount');
  late final _GeniusSDKTransferGeniusAccount =
      _GeniusSDKTransferGeniusAccountPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// @brief Merges an external account into the node's wallet.
  /// @param[in] public_address Null-terminated string representing the account's public address to merge.
  /// @return @ref GENIUS_NODE_RET_OK on success, @ref GENIUS_NODE_ERROR_CREATING if not initialized,
  /// or @ref GENIUS_NODE_INVALID_ARGUMENT on failure.
  int GeniusSDKMergeGeniusAccount(ffi.Pointer<ffi.Char> public_address) {
    return _GeniusSDKMergeGeniusAccount(public_address);
  }

  late final _GeniusSDKMergeGeniusAccountPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(ffi.Pointer<ffi.Char>)
        >
      >('GeniusSDKMergeGeniusAccount');
  late final _GeniusSDKMergeGeniusAccount =
      _GeniusSDKMergeGeniusAccountPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// @brief Deletes the account.
  int GeniusSDKDeleteAccount(ffi.Pointer<ffi.Char> public_address) {
    return _GeniusSDKDeleteAccount(public_address);
  }

  late final _GeniusSDKDeleteAccountPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(ffi.Pointer<ffi.Char>)
        >
      >('GeniusSDKDeleteAccount');
  late final _GeniusSDKDeleteAccount =
      _GeniusSDKDeleteAccountPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// @brief Sets the payout address for processing rewards.
  /// @param[in] public_address Null-terminated string representing the payout public address.
  /// @return @ref GENIUS_NODE_RET_OK on success, @ref GENIUS_NODE_ERROR_CREATING if not initialized,
  /// or @ref GENIUS_NODE_INVALID_ARGUMENT on failure.
  int GeniusSDKSetPayoutAddress(ffi.Pointer<ffi.Char> public_address) {
    return _GeniusSDKSetPayoutAddress(public_address);
  }

  late final _GeniusSDKSetPayoutAddressPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(ffi.Pointer<ffi.Char>)
        >
      >('GeniusSDKSetPayoutAddress');
  late final _GeniusSDKSetPayoutAddress =
      _GeniusSDKSetPayoutAddressPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// @brief Retrieves the current balance for a specific token.
  /// @param[in] token_id  Token identifier to query.
  /// @return The balance amount as a `uint64_t` value (in Minion Tokens).
  int GeniusSDKGetBalance(GeniusTokenID token_id) {
    return _GeniusSDKGetBalance(token_id);
  }

  late final _GeniusSDKGetBalancePtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function(GeniusTokenID)>>(
        'GeniusSDKGetBalance',
      );
  late final _GeniusSDKGetBalance =
      _GeniusSDKGetBalancePtr.asFunction<int Function(GeniusTokenID)>();

  /// @brief Retrieves the current balance in **Genius Tokens** as a formatted string.
  /// @return The balance as a `GeniusTokenValue` struct, containing a GNUS value in string format.
  GeniusTokenValue GeniusSDKGetBalanceGNUS() {
    return _GeniusSDKGetBalanceGNUS();
  }

  late final _GeniusSDKGetBalanceGNUSPtr =
      _lookup<ffi.NativeFunction<GeniusTokenValue Function()>>(
        'GeniusSDKGetBalanceGNUS',
      );
  late final _GeniusSDKGetBalanceGNUS =
      _GeniusSDKGetBalanceGNUSPtr.asFunction<GeniusTokenValue Function()>();

  /// @brief Retrieves the current balance in **Genius Tokens** as a formatted string.
  /// @return A pointer to a null-terminated UTF-8 string representing the current balance in GNUS.
  ffi.Pointer<ffi.Char> GeniusSDKGetBalanceGNUSString() {
    return _GeniusSDKGetBalanceGNUSString();
  }

  late final _GeniusSDKGetBalanceGNUSStringPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'GeniusSDKGetBalanceGNUSString',
      );
  late final _GeniusSDKGetBalanceGNUSString =
      _GeniusSDKGetBalanceGNUSStringPtr.asFunction<
        ffi.Pointer<ffi.Char> Function()
      >();

  /// @brief Retrieves the current USD price of gnus
  /// @return The price as a `double` value in USD.
  double GeniusSDKGetGNUSPrice() {
    return _GeniusSDKGetGNUSPrice();
  }

  late final _GeniusSDKGetGNUSPricePtr =
      _lookup<ffi.NativeFunction<ffi.Double Function()>>(
        'GeniusSDKGetGNUSPrice',
      );
  late final _GeniusSDKGetGNUSPrice =
      _GeniusSDKGetGNUSPricePtr.asFunction<double Function()>();

  /// @brief       Retrieves the SDK version string.
  /// @return      A pointer to a null-terminated UTF-8 string representing the SDK version.
  ffi.Pointer<ffi.Char> GeniusSDKGetVersion() {
    return _GeniusSDKGetVersion();
  }

  late final _GeniusSDKGetVersionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'GeniusSDKGetVersion',
      );
  late final _GeniusSDKGetVersion =
      _GeniusSDKGetVersionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// @brief Returns the public address of the currently selected account.
  /// @return Address filled or zeroized if SDK wasn't initialized.
  GeniusAddress GeniusSDKGetAddress() {
    return _GeniusSDKGetAddress();
  }

  late final _GeniusSDKGetAddressPtr =
      _lookup<ffi.NativeFunction<GeniusAddress Function()>>(
        'GeniusSDKGetAddress',
      );
  late final _GeniusSDKGetAddress =
      _GeniusSDKGetAddressPtr.asFunction<GeniusAddress Function()>();

  /// @brief Returns the mnemonic of the current active account or `nullptr`
  /// if the account was not created from a mnemonic.
  /// @return A heap-allocated null-terminated mnemonic string, or `nullptr` if
  /// the SDK is not initialized or the account has no mnemonic.
  /// Must be freed with @ref GeniusSDKFree.
  GeniusMnemonic GeniusSDKGetMnemonic() {
    return _GeniusSDKGetMnemonic();
  }

  late final _GeniusSDKGetMnemonicPtr =
      _lookup<ffi.NativeFunction<GeniusMnemonic Function()>>(
        'GeniusSDKGetMnemonic',
      );
  late final _GeniusSDKGetMnemonic =
      _GeniusSDKGetMnemonicPtr.asFunction<GeniusMnemonic Function()>();

  /// @brief Retrieves all incoming transactions.
  /// @return A @ref GeniusMatrix containing the incoming transactions.
  /// Must be freed with @ref GeniusSDKFreeTransactions().
  GeniusMatrix GeniusSDKGetInTransactions() {
    return _GeniusSDKGetInTransactions();
  }

  late final _GeniusSDKGetInTransactionsPtr =
      _lookup<ffi.NativeFunction<GeniusMatrix Function()>>(
        'GeniusSDKGetInTransactions',
      );
  late final _GeniusSDKGetInTransactions =
      _GeniusSDKGetInTransactionsPtr.asFunction<GeniusMatrix Function()>();

  /// @brief Retrieves all outgoing transactions.
  /// @return A @ref GeniusMatrix containing the outgoing transactions.
  /// Must be freed with @ref GeniusSDKFreeTransactions().
  GeniusMatrix GeniusSDKGetOutTransactions() {
    return _GeniusSDKGetOutTransactions();
  }

  late final _GeniusSDKGetOutTransactionsPtr =
      _lookup<ffi.NativeFunction<GeniusMatrix Function()>>(
        'GeniusSDKGetOutTransactions',
      );
  late final _GeniusSDKGetOutTransactions =
      _GeniusSDKGetOutTransactionsPtr.asFunction<GeniusMatrix Function()>();

  /// @brief Frees a @ref GeniusMatrix previously obtained from GetInTransactions() or GetOutTransactions().
  /// @param[in] matrix The matrix to free.
  void GeniusSDKFreeTransactions(GeniusMatrix matrix) {
    return _GeniusSDKFreeTransactions(matrix);
  }

  late final _GeniusSDKFreeTransactionsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(GeniusMatrix)>>(
        'GeniusSDKFreeTransactions',
      );
  late final _GeniusSDKFreeTransactions =
      _GeniusSDKFreeTransactionsPtr.asFunction<void Function(GeniusMatrix)>();

  /// @brief     Mints new tokens specified in **Minion Tokens**.
  /// @param[in] amount           The amount to be minted in Minion Tokens.
  /// @param[in] transaction_hash A null-terminated string representing the transaction hash.
  /// @param[in] chain_id         A null-terminated string representing the blockchain chain ID.
  /// @param[in] token_id         Token identifier.
  int GeniusSDKMint(
    int amount,
    ffi.Pointer<ffi.Char> transaction_hash,
    ffi.Pointer<ffi.Char> chain_id,
    GeniusTokenID token_id,
  ) {
    return _GeniusSDKMint(amount, transaction_hash, chain_id, token_id);
  }

  late final _GeniusSDKMintPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(
            ffi.Uint64,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            GeniusTokenID,
          )
        >
      >('GeniusSDKMint');
  late final _GeniusSDKMint =
      _GeniusSDKMintPtr.asFunction<
        int Function(
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          GeniusTokenID,
        )
      >();

  /// @brief     Mints new tokens using a **Genius Token** string format.
  /// @param[in] amount           Pointer to a `GeniusTokenValue` struct representing the amount in GNUS.
  /// @param[in] transaction_hash A null-terminated string representing the transaction hash.
  /// @param[in] chain_id         A null-terminated string representing the blockchain chain ID.
  int GeniusSDKMintGNUS(
    ffi.Pointer<GeniusTokenValue> amount,
    ffi.Pointer<ffi.Char> transaction_hash,
    ffi.Pointer<ffi.Char> chain_id,
  ) {
    return _GeniusSDKMintGNUS(amount, transaction_hash, chain_id);
  }

  late final _GeniusSDKMintGNUSPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(
            ffi.Pointer<GeniusTokenValue>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('GeniusSDKMintGNUS');
  late final _GeniusSDKMintGNUS =
      _GeniusSDKMintGNUSPtr.asFunction<
        int Function(
          ffi.Pointer<GeniusTokenValue>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// @brief     Transfers tokens in **Minion Tokens** to another address.
  /// @param[in] amount    The amount to transfer in Minion Tokens.
  /// @param[in] dest      Pointer to a `GeniusAddress` struct representing the recipient's address.
  /// @param[in] token_id  Token identifier.
  /// @return @ref GENIUS_NODE_RET_OK on success, @ref GENIUS_NODE_ERROR_NOT_INITIALIZED if the SDK is not initialized,
  /// or @ref GENIUS_NODE_ERROR_TRANSFER on failure.
  int GeniusSDKTransfer(
    int amount,
    ffi.Pointer<GeniusAddress> dest,
    GeniusTokenID token_id,
  ) {
    return _GeniusSDKTransfer(amount, dest, token_id);
  }

  late final _GeniusSDKTransferPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(
            ffi.Uint64,
            ffi.Pointer<GeniusAddress>,
            GeniusTokenID,
          )
        >
      >('GeniusSDKTransfer');
  late final _GeniusSDKTransfer =
      _GeniusSDKTransferPtr.asFunction<
        int Function(int, ffi.Pointer<GeniusAddress>, GeniusTokenID)
      >();

  /// @brief     Transfers tokens using a **Genius Token** string representation.
  /// @param[in] amount Pointer to a `GeniusTokenValue` struct representing the amount in GNUS.
  /// @param[in] dest   Pointer to a `GeniusAddress` struct representing the recipient's address.
  /// @return @ref GENIUS_NODE_RET_OK on success, @ref GENIUS_NODE_ERROR_NOT_INITIALIZED if the SDK is not initialized,
  /// @ref GENIUS_NODE_INVALID_ARGUMENT if amount or dest is null,
  /// or @ref GENIUS_NODE_ERROR_TRANSFER on failure.
  int GeniusSDKTransferGNUS(
    ffi.Pointer<GeniusTokenValue> amount,
    ffi.Pointer<GeniusAddress> dest,
  ) {
    return _GeniusSDKTransferGNUS(amount, dest);
  }

  late final _GeniusSDKTransferGNUSPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(
            ffi.Pointer<GeniusTokenValue>,
            ffi.Pointer<GeniusAddress>,
          )
        >
      >('GeniusSDKTransferGNUS');
  late final _GeniusSDKTransferGNUS =
      _GeniusSDKTransferGNUSPtr.asFunction<
        int Function(ffi.Pointer<GeniusTokenValue>, ffi.Pointer<GeniusAddress>)
      >();

  /// @brief     Pays the developer for in-game transactions.
  /// @param[in] amount   The amount to transfer in Minion Tokens.
  /// @param[in] token_id Token identifier.
  /// @return @ref GENIUS_NODE_RET_OK on success, @ref GENIUS_NODE_ERROR_NOT_INITIALIZED if the SDK is not initialized,
  /// or @ref GENIUS_NODE_ERROR_PAY_DEV on failure.
  int GeniusSDKPayDev(int amount, GeniusTokenID token_id) {
    return _GeniusSDKPayDev(amount, token_id);
  }

  late final _GeniusSDKPayDevPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(ffi.Uint64, GeniusTokenID)
        >
      >('GeniusSDKPayDev');
  late final _GeniusSDKPayDev =
      _GeniusSDKPayDevPtr.asFunction<int Function(int, GeniusTokenID)>();

  /// @brief Computes the cost of an operation based on the given JSON data (in **Minion Tokens**).
  /// @param[in] jsondata The JSON data to be processed.
  /// @return A `uint64_t` representing the cost in Minion Tokens.
  int GeniusSDKGetCost(ffi.Pointer<ffi.Char> jsondata) {
    return _GeniusSDKGetCost(jsondata);
  }

  late final _GeniusSDKGetCostPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<ffi.Char>)>>(
        'GeniusSDKGetCost',
      );
  late final _GeniusSDKGetCost =
      _GeniusSDKGetCostPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// @brief Computes the cost of an operation based on the given JSON data (in **Genius Tokens**).
  /// @param[in] jsondata The JSON data to be processed.
  /// @return A `GeniusTokenValue` struct representing the cost in Genius Tokens.
  GeniusTokenValue GeniusSDKGetCostGNUS(ffi.Pointer<ffi.Char> jsondata) {
    return _GeniusSDKGetCostGNUS(jsondata);
  }

  late final _GeniusSDKGetCostGNUSPtr =
      _lookup<
        ffi.NativeFunction<GeniusTokenValue Function(ffi.Pointer<ffi.Char>)>
      >('GeniusSDKGetCostGNUS');
  late final _GeniusSDKGetCostGNUS =
      _GeniusSDKGetCostGNUSPtr.asFunction<
        GeniusTokenValue Function(ffi.Pointer<ffi.Char>)
      >();

  /// @brief Submits data for processing based on the given JSON data.
  /// @param[in] jsondata The JSON data to be processed.
  /// @return A `GeniusNodeReturnValue_t` indicating the result of the operation.
  int GeniusSDKProcess(ffi.Pointer<ffi.Char> jsondata) {
    return _GeniusSDKProcess(jsondata);
  }

  late final _GeniusSDKProcessPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(ffi.Pointer<ffi.Char>)
        >
      >('GeniusSDKProcess');
  late final _GeniusSDKProcess =
      _GeniusSDKProcessPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// @brief Checks the validity of a job based on the given JSON data.
  /// @param[in] jsondata The JSON data to be processed.
  /// @return `true` if the job is valid, `false` otherwise.
  bool GeniusSDKCheckJobValidity(ffi.Pointer<ffi.Char> jsondata) {
    return _GeniusSDKCheckJobValidity(jsondata);
  }

  late final _GeniusSDKCheckJobValidityPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>)>>(
        'GeniusSDKCheckJobValidity',
      );
  late final _GeniusSDKCheckJobValidity =
      _GeniusSDKCheckJobValidityPtr.asFunction<
        bool Function(ffi.Pointer<ffi.Char>)
      >();

  /// @brief       Retrieves the current state of the Transaction Manager.
  /// @return      The current state as a @ref GeniusTransactionManagerState enum value.
  int GeniusSDKGetTransactionManagerState() {
    return _GeniusSDKGetTransactionManagerState();
  }

  late final _GeniusSDKGetTransactionManagerStatePtr =
      _lookup<ffi.NativeFunction<GeniusTransactionManagerState_t Function()>>(
        'GeniusSDKGetTransactionManagerState',
      );
  late final _GeniusSDKGetTransactionManagerState =
      _GeniusSDKGetTransactionManagerStatePtr.asFunction<int Function()>();

  /// @brief       Retrieves the current state of the Genius Node.
  /// @return      The current state as a @ref GeniusNodeState enum value.
  int GeniusSDKGetNodeState() {
    return _GeniusSDKGetNodeState();
  }

  late final _GeniusSDKGetNodeStatePtr =
      _lookup<ffi.NativeFunction<GeniusNodeState_t Function()>>(
        'GeniusSDKGetNodeState',
      );
  late final _GeniusSDKGetNodeState =
      _GeniusSDKGetNodeStatePtr.asFunction<int Function()>();

  /// @brief       Retrieves the status of a specific transaction.
  /// @param[in]   tx_id A null-terminated string representing the transaction ID.
  /// @return      The transaction status as a @ref GeniusTransactionStatus enum value.
  int GeniusSDKGetTransactionStatus(ffi.Pointer<ffi.Char> tx_id) {
    return _GeniusSDKGetTransactionStatus(tx_id);
  }

  late final _GeniusSDKGetTransactionStatusPtr =
      _lookup<
        ffi.NativeFunction<
          GeniusTransactionStatus_t Function(ffi.Pointer<ffi.Char>)
        >
      >('GeniusSDKGetTransactionStatus');
  late final _GeniusSDKGetTransactionStatus =
      _GeniusSDKGetTransactionStatusPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// @brief       Retrieves the current processing status with progress information.
  /// @return      A @ref GeniusProcessingStatusInfo struct containing the processing status and percentage.
  GeniusProcessingStatusInfo GeniusSDKGetProcessingStatus() {
    return _GeniusSDKGetProcessingStatus();
  }

  late final _GeniusSDKGetProcessingStatusPtr =
      _lookup<ffi.NativeFunction<GeniusProcessingStatusInfo Function()>>(
        'GeniusSDKGetProcessingStatus',
      );
  late final _GeniusSDKGetProcessingStatus =
      _GeniusSDKGetProcessingStatusPtr.asFunction<
        GeniusProcessingStatusInfo Function()
      >();

  /// @brief       Returns the task IDs of jobs submitted by the active account.
  /// @param[in]   limit  Maximum number of task IDs to return.
  /// @param[in]   offset Number of task IDs to skip from the end of the list.
  /// @return      A null-terminated string containing newline-separated task IDs,
  /// or null if the SDK is not initialized. Must be freed with GeniusSDKFree().
  ffi.Pointer<ffi.Char> GeniusSDKGetMyTaskIds(int limit, int offset) {
    return _GeniusSDKGetMyTaskIds(limit, offset);
  }

  late final _GeniusSDKGetMyTaskIdsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Uint64, ffi.Uint64)
        >
      >('GeniusSDKGetMyTaskIds');
  late final _GeniusSDKGetMyTaskIds =
      _GeniusSDKGetMyTaskIdsPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(int, int)
      >();

  /// @brief       Retrieves the completed result for a specific task.
  /// @param[in]   task_id A null-terminated string representing the task ID (ipfs_block_id).
  /// @return      A GeniusArray containing the serialized protobuf bytes of TaskResult,
  /// or {0, nullptr} if the task is not found or SDK is not initialized.
  /// On success, the ptr field must be freed with GeniusSDKFree().
  GeniusArray GeniusSDKGetTaskResult(ffi.Pointer<ffi.Char> task_id) {
    return _GeniusSDKGetTaskResult(task_id);
  }

  late final _GeniusSDKGetTaskResultPtr =
      _lookup<ffi.NativeFunction<GeniusArray Function(ffi.Pointer<ffi.Char>)>>(
        'GeniusSDKGetTaskResult',
      );
  late final _GeniusSDKGetTaskResult =
      _GeniusSDKGetTaskResultPtr.asFunction<
        GeniusArray Function(ffi.Pointer<ffi.Char>)
      >();
}

typedef __u_char = ffi.UnsignedChar;
typedef Dart__u_char = int;
typedef __u_short = ffi.UnsignedShort;
typedef Dart__u_short = int;
typedef __u_int = ffi.UnsignedInt;
typedef Dart__u_int = int;
typedef __u_long = ffi.UnsignedLong;
typedef Dart__u_long = int;
typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __int64_t = ffi.Long;
typedef Dart__int64_t = int;
typedef __uint64_t = ffi.UnsignedLong;
typedef Dart__uint64_t = int;
typedef __int_least8_t = __int8_t;
typedef __uint_least8_t = __uint8_t;
typedef __int_least16_t = __int16_t;
typedef __uint_least16_t = __uint16_t;
typedef __int_least32_t = __int32_t;
typedef __uint_least32_t = __uint32_t;
typedef __int_least64_t = __int64_t;
typedef __uint_least64_t = __uint64_t;
typedef __quad_t = ffi.Long;
typedef Dart__quad_t = int;
typedef __u_quad_t = ffi.UnsignedLong;
typedef Dart__u_quad_t = int;
typedef __intmax_t = ffi.Long;
typedef Dart__intmax_t = int;
typedef __uintmax_t = ffi.UnsignedLong;
typedef Dart__uintmax_t = int;
typedef __dev_t = ffi.UnsignedLong;
typedef Dart__dev_t = int;
typedef __uid_t = ffi.UnsignedInt;
typedef Dart__uid_t = int;
typedef __gid_t = ffi.UnsignedInt;
typedef Dart__gid_t = int;
typedef __ino_t = ffi.UnsignedLong;
typedef Dart__ino_t = int;
typedef __ino64_t = ffi.UnsignedLong;
typedef Dart__ino64_t = int;
typedef __mode_t = ffi.UnsignedInt;
typedef Dart__mode_t = int;
typedef __nlink_t = ffi.UnsignedLong;
typedef Dart__nlink_t = int;
typedef __off_t = ffi.Long;
typedef Dart__off_t = int;
typedef __off64_t = ffi.Long;
typedef Dart__off64_t = int;
typedef __pid_t = ffi.Int;
typedef Dart__pid_t = int;

final class __fsid_t extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> __val;
}

typedef __clock_t = ffi.Long;
typedef Dart__clock_t = int;
typedef __rlim_t = ffi.UnsignedLong;
typedef Dart__rlim_t = int;
typedef __rlim64_t = ffi.UnsignedLong;
typedef Dart__rlim64_t = int;
typedef __id_t = ffi.UnsignedInt;
typedef Dart__id_t = int;
typedef __time_t = ffi.Long;
typedef Dart__time_t = int;
typedef __useconds_t = ffi.UnsignedInt;
typedef Dart__useconds_t = int;
typedef __suseconds_t = ffi.Long;
typedef Dart__suseconds_t = int;
typedef __suseconds64_t = ffi.Long;
typedef Dart__suseconds64_t = int;
typedef __daddr_t = ffi.Int;
typedef Dart__daddr_t = int;
typedef __key_t = ffi.Int;
typedef Dart__key_t = int;
typedef __clockid_t = ffi.Int;
typedef Dart__clockid_t = int;
typedef __timer_t = ffi.Pointer<ffi.Void>;
typedef __blksize_t = ffi.Long;
typedef Dart__blksize_t = int;
typedef __blkcnt_t = ffi.Long;
typedef Dart__blkcnt_t = int;
typedef __blkcnt64_t = ffi.Long;
typedef Dart__blkcnt64_t = int;
typedef __fsblkcnt_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt_t = int;
typedef __fsblkcnt64_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt64_t = int;
typedef __fsfilcnt_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt_t = int;
typedef __fsfilcnt64_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt64_t = int;
typedef __fsword_t = ffi.Long;
typedef Dart__fsword_t = int;
typedef __ssize_t = ffi.Long;
typedef Dart__ssize_t = int;
typedef __syscall_slong_t = ffi.Long;
typedef Dart__syscall_slong_t = int;
typedef __syscall_ulong_t = ffi.UnsignedLong;
typedef Dart__syscall_ulong_t = int;
typedef __loff_t = __off64_t;
typedef __caddr_t = ffi.Pointer<ffi.Char>;
typedef __intptr_t = ffi.Long;
typedef Dart__intptr_t = int;
typedef __socklen_t = ffi.UnsignedInt;
typedef Dart__socklen_t = int;
typedef __sig_atomic_t = ffi.Int;
typedef Dart__sig_atomic_t = int;
typedef int_least8_t = __int_least8_t;
typedef int_least16_t = __int_least16_t;
typedef int_least32_t = __int_least32_t;
typedef int_least64_t = __int_least64_t;
typedef uint_least8_t = __uint_least8_t;
typedef uint_least16_t = __uint_least16_t;
typedef uint_least32_t = __uint_least32_t;
typedef uint_least64_t = __uint_least64_t;
typedef int_fast8_t = ffi.SignedChar;
typedef Dartint_fast8_t = int;
typedef int_fast16_t = ffi.Long;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Long;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.Long;
typedef Dartint_fast64_t = int;
typedef uint_fast8_t = ffi.UnsignedChar;
typedef Dartuint_fast8_t = int;
typedef uint_fast16_t = ffi.UnsignedLong;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.UnsignedLong;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.UnsignedLong;
typedef Dartuint_fast64_t = int;
typedef intmax_t = __intmax_t;
typedef uintmax_t = __uintmax_t;

final class GeniusArray extends ffi.Struct {
  @ffi.Uint64()
  external int size;

  external ffi.Pointer<ffi.Uint8> ptr;
}

final class GeniusMatrix extends ffi.Struct {
  @ffi.Uint64()
  external int size;

  external ffi.Pointer<GeniusArray> ptr;
}

final class GeniusAddress extends ffi.Struct {
  /// A string prepended with `0x` followed by 128 hex characters,
  /// including a null-terminating char just for safety.
  @ffi.Array.multi([131])
  external ffi.Array<ffi.Char> address;
}

/// @brief Represents a Genius token value in fixed-point format as a string.
///
/// This structure provides enough space to hold the largest possible Genius token
/// string value ("18446744073709.551615") plus the null terminator.
final class GeniusTokenValue extends ffi.Struct {
  /// < String representation of the Genius token value
  @ffi.Array.multi([22])
  external ffi.Array<ffi.Char> value;
}

/// @brief A binary identifier for a Genius-compatible token.
final class GeniusTokenID extends ffi.Struct {
  /// < 32-byte raw token ID used internally
  @ffi.Array.multi([32])
  external ffi.Array<ffi.UnsignedChar> data;
}

typedef PayAmount_t = ffi.Uint64;
typedef DartPayAmount_t = int;
typedef GeniusNodeReturnValue_t = ffi.Int32;
typedef DartGeniusNodeReturnValue_t = int;
typedef GeniusNodeState_t = ffi.Int32;
typedef DartGeniusNodeState_t = int;
typedef GeniusTransactionManagerState_t = ffi.Int32;
typedef DartGeniusTransactionManagerState_t = int;
typedef GeniusTransactionStatus_t = ffi.Int32;
typedef DartGeniusTransactionStatus_t = int;
typedef GeniusProcessingStatus_t = ffi.Int32;
typedef DartGeniusProcessingStatus_t = int;

enum GeniusNodeReturnValue {
  GENIUS_NODE_RET_OK(0),
  GENIUS_NODE_ERROR_NOT_INITIALIZED(1),
  GENIUS_NODE_ERROR_PROCESS_IMAGE(2),
  GENIUS_NODE_ERROR_MINT(3),
  GENIUS_NODE_INVALID_ARGUMENT(4),
  GENIUS_NODE_ERROR_TRANSFER(5),
  GENIUS_NODE_ERROR_PAY_DEV(6);

  final int value;
  const GeniusNodeReturnValue(this.value);

  static GeniusNodeReturnValue fromValue(int value) => switch (value) {
    0 => GENIUS_NODE_RET_OK,
    1 => GENIUS_NODE_ERROR_NOT_INITIALIZED,
    2 => GENIUS_NODE_ERROR_PROCESS_IMAGE,
    3 => GENIUS_NODE_ERROR_MINT,
    4 => GENIUS_NODE_INVALID_ARGUMENT,
    5 => GENIUS_NODE_ERROR_TRANSFER,
    6 => GENIUS_NODE_ERROR_PAY_DEV,
    _ => throw ArgumentError('Unknown value for GeniusNodeReturnValue: $value'),
  };
}

/// @brief Node state enumeration (maps to GeniusNode::NodeState)
/// Values must match GeniusNode::NodeState enum values
enum GeniusNodeState {
  GENIUS_NODE_CREATING(0),
  GENIUS_NODE_MIGRATING_DATABASE(1),
  GENIUS_NODE_INITIALIZING_DATABASE(2),
  GENIUS_NODE_INITIALIZING_PROCESSING(3),
  GENIUS_NODE_INITIALIZING_BLOCKCHAIN(4),
  GENIUS_NODE_INITIALIZING_TRANSACTIONS(5),
  GENIUS_NODE_INITIALIZING_DHT(6),
  GENIUS_NODE_READY(7);

  final int value;
  const GeniusNodeState(this.value);

  static GeniusNodeState fromValue(int value) => switch (value) {
    0 => GENIUS_NODE_CREATING,
    1 => GENIUS_NODE_MIGRATING_DATABASE,
    2 => GENIUS_NODE_INITIALIZING_DATABASE,
    3 => GENIUS_NODE_INITIALIZING_PROCESSING,
    4 => GENIUS_NODE_INITIALIZING_BLOCKCHAIN,
    5 => GENIUS_NODE_INITIALIZING_TRANSACTIONS,
    6 => GENIUS_NODE_INITIALIZING_DHT,
    7 => GENIUS_NODE_READY,
    _ => throw ArgumentError('Unknown value for GeniusNodeState: $value'),
  };
}

enum GeniusTransactionManagerState {
  /// < Creating the object
  GENIUS_TM_STATE_CREATING(0),

  /// < Initializing the object
  GENIUS_TM_STATE_INITIALIZING(1),

  /// < Synching the transactions
  GENIUS_TM_STATE_SYNCHING(2),

  /// < Ready to process transactions
  GENIUS_TM_STATE_READY(3);

  final int value;
  const GeniusTransactionManagerState(this.value);

  static GeniusTransactionManagerState fromValue(int value) => switch (value) {
    0 => GENIUS_TM_STATE_CREATING,
    1 => GENIUS_TM_STATE_INITIALIZING,
    2 => GENIUS_TM_STATE_SYNCHING,
    3 => GENIUS_TM_STATE_READY,
    _ => throw ArgumentError(
      'Unknown value for GeniusTransactionManagerState: $value',
    ),
  };
}

/// @brief Transaction Status enumeration (maps to TransactionManager::TransactionStatus)
/// Values must match TransactionManager::TransactionStatus enum values
enum GeniusTransactionStatus {
  /// < Transaction created but not yet sent
  GENIUS_TX_STATUS_CREATED(0),

  /// < Transaction is being sent
  GENIUS_TX_STATUS_SENDING(1),

  /// < Transaction confirmed
  GENIUS_TX_STATUS_CONFIRMED(2),

  /// < Transaction being verified
  GENIUS_TX_STATUS_VERIFYING(3),

  /// < Transaction failed
  GENIUS_TX_STATUS_FAILED(4),

  /// < Invalid transaction
  GENIUS_TX_STATUS_INVALID(5);

  final int value;
  const GeniusTransactionStatus(this.value);

  static GeniusTransactionStatus fromValue(int value) => switch (value) {
    0 => GENIUS_TX_STATUS_CREATED,
    1 => GENIUS_TX_STATUS_SENDING,
    2 => GENIUS_TX_STATUS_CONFIRMED,
    3 => GENIUS_TX_STATUS_VERIFYING,
    4 => GENIUS_TX_STATUS_FAILED,
    5 => GENIUS_TX_STATUS_INVALID,
    _ => throw ArgumentError(
      'Unknown value for GeniusTransactionStatus: $value',
    ),
  };
}

enum GeniusProcessingStatus {
  /// < Processing was disabled
  GENIUS_PR_STATUS_DISABLED(0),

  /// < Not processing at the moment
  GENIUS_PR_STATUS_IDLE(1),

  /// < Currently processing a job s
  GENIUS_PR_STATUS_PROCESSING(2);

  final int value;
  const GeniusProcessingStatus(this.value);

  static GeniusProcessingStatus fromValue(int value) => switch (value) {
    0 => GENIUS_PR_STATUS_DISABLED,
    1 => GENIUS_PR_STATUS_IDLE,
    2 => GENIUS_PR_STATUS_PROCESSING,
    _ => throw ArgumentError(
      'Unknown value for GeniusProcessingStatus: $value',
    ),
  };
}

/// @brief Represents the current processing status with progress information.
final class GeniusProcessingStatusInfo extends ffi.Struct {
  /// < Current processing state
  @GeniusProcessingStatus_t()
  external int status;

  /// < Progress percentage from 0.0 to 100.0
  @ffi.Float()
  external double percentage;
}

final class GeniusStatusInfo extends ffi.Struct {
  @ffi.Float()
  external double percentage;

  external ffi.Pointer<ffi.Char> message;
}

final class GeniusMnemonic extends ffi.Struct {
  @ffi.Array.multi([216])
  external ffi.Array<ffi.Char> mnemonic;
}

/// @brief Return type for account creation that includes both a status code and
/// the generated mnemonic phrase.
final class GeniusMnemonicAndStatus extends ffi.Struct {
  /// < Return status (@ref GENIUS_NODE_RET_OK or @ref GENIUS_NODE_ERROR_NOT_INITIALIZED)
  @GeniusProcessingStatus_t()
  external int status;

  /// < Null terminated string
  @ffi.Array.multi([216])
  external ffi.Array<ffi.Char> mnemonic;
}

/// @brief Return type for SDK initialization with a random mnemonic, bundling
/// the initialization path and the generated recovery phrase.
final class GeniusMnemonicAndInitPath extends ffi.Struct {
  /// < Statically allocated, do not call free
  external ffi.Pointer<ffi.Char> initialization_path;

  @ffi.Array.multi([216])
  external ffi.Array<ffi.Char> mnemonic;
}

const int _STDINT_H = 1;

const int _FEATURES_H = 1;

const int _DEFAULT_SOURCE = 1;

const int __GLIBC_USE_ISOC2X = 1;

const int __USE_ISOC11 = 1;

const int __USE_ISOC99 = 1;

const int __USE_ISOC95 = 1;

const int _POSIX_SOURCE = 1;

const int _POSIX_C_SOURCE = 200809;

const int __USE_POSIX = 1;

const int __USE_POSIX2 = 1;

const int __USE_POSIX199309 = 1;

const int __USE_POSIX199506 = 1;

const int __USE_XOPEN2K = 1;

const int __USE_XOPEN2K8 = 1;

const int _ATFILE_SOURCE = 1;

const int __WORDSIZE = 64;

const int __WORDSIZE_TIME64_COMPAT32 = 1;

const int __SYSCALL_WORDSIZE = 64;

const int __TIMESIZE = 64;

const int __USE_MISC = 1;

const int __USE_ATFILE = 1;

const int __USE_FORTIFY_LEVEL = 0;

const int __GLIBC_USE_DEPRECATED_GETS = 0;

const int __GLIBC_USE_DEPRECATED_SCANF = 0;

const int __GLIBC_USE_C2X_STRTOL = 1;

const int _STDC_PREDEF_H = 1;

const int __STDC_IEC_559__ = 1;

const int __STDC_IEC_60559_BFP__ = 201404;

const int __STDC_IEC_559_COMPLEX__ = 1;

const int __STDC_IEC_60559_COMPLEX__ = 201404;

const int __STDC_ISO_10646__ = 201706;

const int __GNU_LIBRARY__ = 6;

const int __GLIBC__ = 2;

const int __GLIBC_MINOR__ = 39;

const int _SYS_CDEFS_H = 1;

const int __THROW = 1;

const int __THROWNL = 1;

const int __glibc_c99_flexarr_available = 1;

const int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI = 0;

const int __HAVE_GENERIC_SELECTION = 0;

const int __GLIBC_USE_LIB_EXT2 = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_TYPES_EXT = 1;

const int _BITS_TYPES_H = 1;

const int _BITS_TYPESIZES_H = 1;

const int __OFF_T_MATCHES_OFF64_T = 1;

const int __INO_T_MATCHES_INO64_T = 1;

const int __RLIM_T_MATCHES_RLIM64_T = 1;

const int __STATFS_MATCHES_STATFS64 = 1;

const int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 = 1;

const int __FD_SETSIZE = 1024;

const int _BITS_TIME64_H = 1;

const int _BITS_WCHAR_H = 1;

const int __WCHAR_MAX = 2147483647;

const int __WCHAR_MIN = -2147483648;

const int _BITS_STDINT_INTN_H = 1;

const int _BITS_STDINT_UINTN_H = 1;

const int _BITS_STDINT_LEAST_H = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -9223372036854775808;

const int INT_FAST32_MIN = -9223372036854775808;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 9223372036854775807;

const int INT_FAST32_MAX = 9223372036854775807;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = -1;

const int UINT_FAST32_MAX = -1;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int SIZE_MAX = -1;

const int WCHAR_MIN = -2147483648;

const int WCHAR_MAX = 2147483647;

const int WINT_MIN = 0;

const int WINT_MAX = 4294967295;

const int __bool_true_false_are_defined = 1;

const int true$ = 1;

const int false$ = 0;

const int GENIUS_SDK_ADDRESS_SIZE = 130;

const int GENIUS_SDK_MAX_MNEMONIC_SIZE = 216;
