// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Char> GeniusSDKInit(
    ffi.Pointer<ffi.Char> base_path,
    ffi.Pointer<ffi.Char> eth_private_key,
    bool autodht,
    bool process,
    int baseport,
    bool is_full_node,
  ) {
    return _GeniusSDKInit(
      base_path,
      eth_private_key,
      autodht,
      process,
      baseport,
      is_full_node,
    );
  }

  late final _GeniusSDKInitPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Bool,
              ffi.Bool,
              ffi.Uint16,
              ffi.Bool)>>('GeniusSDKInit');
  late final _GeniusSDKInit = _GeniusSDKInitPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, bool, bool, int, bool)>();

  ffi.Pointer<ffi.Char> GeniusSDKInitSecure(
    ffi.Pointer<ffi.Char> base_path,
    ffi.Pointer<ffi.Char> dev_config,
    ffi.Pointer<ffi.Char> eth_private_key,
    bool autodht,
    bool process,
    int baseport,
    bool is_full_node,
  ) {
    return _GeniusSDKInitSecure(
      base_path,
      dev_config,
      eth_private_key,
      autodht,
      process,
      baseport,
      is_full_node,
    );
  }

  late final _GeniusSDKInitSecurePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Bool,
              ffi.Bool,
              ffi.Uint16,
              ffi.Bool)>>('GeniusSDKInitSecure');
  late final _GeniusSDKInitSecure = _GeniusSDKInitSecurePtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          bool,
          bool,
          int,
          bool)>();

  ffi.Pointer<ffi.Char> GeniusSDKInitMinimal(
    ffi.Pointer<ffi.Char> base_path,
    ffi.Pointer<ffi.Char> eth_private_key,
    int baseport,
  ) {
    return _GeniusSDKInitMinimal(
      base_path,
      eth_private_key,
      baseport,
    );
  }

  late final _GeniusSDKInitMinimalPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Uint16)>>('GeniusSDKInitMinimal');
  late final _GeniusSDKInitMinimal = _GeniusSDKInitMinimalPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)>();

  int GeniusSDKShutdown() {
    return _GeniusSDKShutdown();
  }

  late final _GeniusSDKShutdownPtr =
      _lookup<ffi.NativeFunction<GeniusNodeReturnValue_t Function()>>(
          'GeniusSDKShutdown');
  late final _GeniusSDKShutdown =
      _GeniusSDKShutdownPtr.asFunction<int Function()>();

  /// @brief Retrieves the current balance for a specific token.
  /// @param[in] token_id  Token identifier to query.
  /// @return The balance amount as a `uint64_t` value (in Minion Tokens).
  int GeniusSDKGetBalance(
    GeniusTokenID token_id,
  ) {
    return _GeniusSDKGetBalance(
      token_id,
    );
  }

  late final _GeniusSDKGetBalancePtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function(GeniusTokenID)>>(
          'GeniusSDKGetBalance');
  late final _GeniusSDKGetBalance =
      _GeniusSDKGetBalancePtr.asFunction<int Function(GeniusTokenID)>();

  /// @brief Retrieves the current balance in **Genius Tokens** as a formatted string.
  /// @return The balance as a `GeniusTokenValue` struct, containing a GNUS value in string format.
  GeniusTokenValue GeniusSDKGetBalanceGNUS() {
    return _GeniusSDKGetBalanceGNUS();
  }

  late final _GeniusSDKGetBalanceGNUSPtr =
      _lookup<ffi.NativeFunction<GeniusTokenValue Function()>>(
          'GeniusSDKGetBalanceGNUS');
  late final _GeniusSDKGetBalanceGNUS =
      _GeniusSDKGetBalanceGNUSPtr.asFunction<GeniusTokenValue Function()>();

  /// @brief Retrieves the current balance in **Genius Tokens** as a formatted string.
  /// @return A pointer to a null-terminated UTF-8 string representing the current balance in GNUS.
  ffi.Pointer<ffi.Char> GeniusSDKGetBalanceGNUSString() {
    return _GeniusSDKGetBalanceGNUSString();
  }

  late final _GeniusSDKGetBalanceGNUSStringPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'GeniusSDKGetBalanceGNUSString');
  late final _GeniusSDKGetBalanceGNUSString = _GeniusSDKGetBalanceGNUSStringPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// @brief Retrieves the current USD price of gnus
  /// @return The price as a `double` value in USD.
  double GeniusSDKGetGNUSPrice() {
    return _GeniusSDKGetGNUSPrice();
  }

  late final _GeniusSDKGetGNUSPricePtr =
      _lookup<ffi.NativeFunction<ffi.Double Function()>>(
          'GeniusSDKGetGNUSPrice');
  late final _GeniusSDKGetGNUSPrice =
      _GeniusSDKGetGNUSPricePtr.asFunction<double Function()>();

  /// @brief       Retrieves the SDK version string.
  /// @return      A pointer to a null-terminated UTF-8 string representing the SDK version.
  ffi.Pointer<ffi.Char> GeniusSDKGetVersion() {
    return _GeniusSDKGetVersion();
  }

  late final _GeniusSDKGetVersionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'GeniusSDKGetVersion');
  late final _GeniusSDKGetVersion =
      _GeniusSDKGetVersionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  GeniusAddress GeniusSDKGetAddress() {
    return _GeniusSDKGetAddress();
  }

  late final _GeniusSDKGetAddressPtr =
      _lookup<ffi.NativeFunction<GeniusAddress Function()>>(
          'GeniusSDKGetAddress');
  late final _GeniusSDKGetAddress =
      _GeniusSDKGetAddressPtr.asFunction<GeniusAddress Function()>();

  GeniusMatrix GeniusSDKGetInTransactions() {
    return _GeniusSDKGetInTransactions();
  }

  late final _GeniusSDKGetInTransactionsPtr =
      _lookup<ffi.NativeFunction<GeniusMatrix Function()>>(
          'GeniusSDKGetInTransactions');
  late final _GeniusSDKGetInTransactions =
      _GeniusSDKGetInTransactionsPtr.asFunction<GeniusMatrix Function()>();

  GeniusMatrix GeniusSDKGetOutTransactions() {
    return _GeniusSDKGetOutTransactions();
  }

  late final _GeniusSDKGetOutTransactionsPtr =
      _lookup<ffi.NativeFunction<GeniusMatrix Function()>>(
          'GeniusSDKGetOutTransactions');
  late final _GeniusSDKGetOutTransactions =
      _GeniusSDKGetOutTransactionsPtr.asFunction<GeniusMatrix Function()>();

  void GeniusSDKFreeTransactions(
    GeniusMatrix matrix,
  ) {
    return _GeniusSDKFreeTransactions(
      matrix,
    );
  }

  late final _GeniusSDKFreeTransactionsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(GeniusMatrix)>>(
          'GeniusSDKFreeTransactions');
  late final _GeniusSDKFreeTransactions =
      _GeniusSDKFreeTransactionsPtr.asFunction<void Function(GeniusMatrix)>();

  /// @brief     Mints new tokens specified in **Minion Tokens**.
  /// @param[in] amount           The amount to be minted in Minion Tokens.
  /// @param[in] transaction_hash A null-terminated string representing the transaction hash.
  /// @param[in] chain_id         A null-terminated string representing the blockchain chain ID.
  /// @param[in] token_id         Token identifier.
  int GeniusSDKMint(
    int amount,
    ffi.Pointer<ffi.Char> transaction_hash,
    ffi.Pointer<ffi.Char> chain_id,
    GeniusTokenID token_id,
  ) {
    return _GeniusSDKMint(
      amount,
      transaction_hash,
      chain_id,
      token_id,
    );
  }

  late final _GeniusSDKMintPtr = _lookup<
      ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(ffi.Uint64, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, GeniusTokenID)>>('GeniusSDKMint');
  late final _GeniusSDKMint = _GeniusSDKMintPtr.asFunction<
      int Function(
          int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, GeniusTokenID)>();

  /// @brief     Mints new tokens using a **Genius Token** string format.
  /// @param[in] amount           Pointer to a `GeniusTokenValue` struct representing the amount in GNUS.
  /// @param[in] transaction_hash A null-terminated string representing the transaction hash.
  /// @param[in] chain_id         A null-terminated string representing the blockchain chain ID.
  int GeniusSDKMintGNUS(
    ffi.Pointer<GeniusTokenValue> amount,
    ffi.Pointer<ffi.Char> transaction_hash,
    ffi.Pointer<ffi.Char> chain_id,
  ) {
    return _GeniusSDKMintGNUS(
      amount,
      transaction_hash,
      chain_id,
    );
  }

  late final _GeniusSDKMintGNUSPtr = _lookup<
      ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(
              ffi.Pointer<GeniusTokenValue>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('GeniusSDKMintGNUS');
  late final _GeniusSDKMintGNUS = _GeniusSDKMintGNUSPtr.asFunction<
      int Function(ffi.Pointer<GeniusTokenValue>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  /// @brief     Transfers tokens in **Minion Tokens** to another address.
  /// @param[in] amount    The amount to transfer in Minion Tokens.
  /// @param[in] dest      Pointer to a `GeniusAddress` struct representing the recipient's address.
  /// @param[in] token_id  Token identifier.
  /// @return `true` if the transfer is successful, `false` otherwise.
  int GeniusSDKTransfer(
    int amount,
    ffi.Pointer<GeniusAddress> dest,
    GeniusTokenID token_id,
  ) {
    return _GeniusSDKTransfer(
      amount,
      dest,
      token_id,
    );
  }

  late final _GeniusSDKTransferPtr = _lookup<
      ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(ffi.Uint64,
              ffi.Pointer<GeniusAddress>, GeniusTokenID)>>('GeniusSDKTransfer');
  late final _GeniusSDKTransfer = _GeniusSDKTransferPtr.asFunction<
      int Function(int, ffi.Pointer<GeniusAddress>, GeniusTokenID)>();

  /// @brief     Transfers tokens using a **Genius Token** string representation.
  /// @param[in] amount Pointer to a `GeniusTokenValue` struct representing the amount in GNUS.
  /// @param[in] dest Pointer to a `GeniusAddress` struct representing the recipient's address.
  /// @return `true` if the transfer is successful, `false` otherwise.
  int GeniusSDKTransferGNUS(
    ffi.Pointer<GeniusTokenValue> amount,
    ffi.Pointer<GeniusAddress> dest,
  ) {
    return _GeniusSDKTransferGNUS(
      amount,
      dest,
    );
  }

  late final _GeniusSDKTransferGNUSPtr = _lookup<
      ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(ffi.Pointer<GeniusTokenValue>,
              ffi.Pointer<GeniusAddress>)>>('GeniusSDKTransferGNUS');
  late final _GeniusSDKTransferGNUS = _GeniusSDKTransferGNUSPtr.asFunction<
      int Function(
          ffi.Pointer<GeniusTokenValue>, ffi.Pointer<GeniusAddress>)>();

  /// @brief     Pays the developer for in-game transactions.
  /// @param[in] amount The amount to transfer in Minion Tokens.
  /// @param[in] token_id token identifier.
  /// @return `true` if the transfer is successful, `false` otherwise.
  int GeniusSDKPayDev(
    int amount,
    GeniusTokenID token_id,
  ) {
    return _GeniusSDKPayDev(
      amount,
      token_id,
    );
  }

  late final _GeniusSDKPayDevPtr = _lookup<
      ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(
              ffi.Uint64, GeniusTokenID)>>('GeniusSDKPayDev');
  late final _GeniusSDKPayDev =
      _GeniusSDKPayDevPtr.asFunction<int Function(int, GeniusTokenID)>();

  /// @brief Computes the cost of an operation based on the given JSON data (in **Minion Tokens**).
  /// @param[in] jsondata The JSON data to be processed.
  /// @return A `uint64_t` representing the cost in Minion Tokens.
  int GeniusSDKGetCost(
    ffi.Pointer<ffi.Char> jsondata,
  ) {
    return _GeniusSDKGetCost(
      jsondata,
    );
  }

  late final _GeniusSDKGetCostPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<ffi.Char>)>>(
          'GeniusSDKGetCost');
  late final _GeniusSDKGetCost =
      _GeniusSDKGetCostPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// @brief Computes the cost of an operation based on the given JSON data (in **Genius Tokens**).
  /// @param[in] jsondata The JSON data to be processed.
  /// @return A `GeniusTokenValue` struct representing the cost in Genius Tokens.
  GeniusTokenValue GeniusSDKGetCostGNUS(
    ffi.Pointer<ffi.Char> jsondata,
  ) {
    return _GeniusSDKGetCostGNUS(
      jsondata,
    );
  }

  late final _GeniusSDKGetCostGNUSPtr = _lookup<
          ffi.NativeFunction<GeniusTokenValue Function(ffi.Pointer<ffi.Char>)>>(
      'GeniusSDKGetCostGNUS');
  late final _GeniusSDKGetCostGNUS = _GeniusSDKGetCostGNUSPtr.asFunction<
      GeniusTokenValue Function(ffi.Pointer<ffi.Char>)>();

  int GeniusSDKProcess(
    ffi.Pointer<ffi.Char> jsondata,
  ) {
    return _GeniusSDKProcess(
      jsondata,
    );
  }

  late final _GeniusSDKProcessPtr = _lookup<
      ffi.NativeFunction<
          GeniusNodeReturnValue_t Function(
              ffi.Pointer<ffi.Char>)>>('GeniusSDKProcess');
  late final _GeniusSDKProcess =
      _GeniusSDKProcessPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// @brief       Retrieves the current state of the Transaction Manager.
  /// @return      The current state as a @ref GeniusTransactionManagerState enum value.
  int GeniusSDKGetTransactionManagerState() {
    return _GeniusSDKGetTransactionManagerState();
  }

  late final _GeniusSDKGetTransactionManagerStatePtr =
      _lookup<ffi.NativeFunction<GeniusTransactionManagerState_t Function()>>(
          'GeniusSDKGetTransactionManagerState');
  late final _GeniusSDKGetTransactionManagerState =
      _GeniusSDKGetTransactionManagerStatePtr.asFunction<int Function()>();

  /// @brief       Retrieves the current state of the Genius Node.
  /// @return      The current state as a @ref GeniusNodeState enum value.
  int GeniusSDKGetNodeState() {
    return _GeniusSDKGetNodeState();
  }

  late final _GeniusSDKGetNodeStatePtr =
      _lookup<ffi.NativeFunction<GeniusNodeState_t Function()>>(
          'GeniusSDKGetNodeState');
  late final _GeniusSDKGetNodeState =
      _GeniusSDKGetNodeStatePtr.asFunction<int Function()>();

  /// @brief       Retrieves the status of a specific transaction.
  /// @param[in]   tx_id A null-terminated string representing the transaction ID.
  /// @return      The transaction status as a @ref GeniusTransactionStatus enum value.
  int GeniusSDKGetTransactionStatus(
    ffi.Pointer<ffi.Char> tx_id,
  ) {
    return _GeniusSDKGetTransactionStatus(
      tx_id,
    );
  }

  late final _GeniusSDKGetTransactionStatusPtr = _lookup<
      ffi.NativeFunction<
          GeniusTransactionStatus_t Function(
              ffi.Pointer<ffi.Char>)>>('GeniusSDKGetTransactionStatus');
  late final _GeniusSDKGetTransactionStatus = _GeniusSDKGetTransactionStatusPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// @brief       Retrieves the current processing status.
  /// @return      The current processing status as a @ref GeniusProcessingStatus enum value.
  int GeniusSDKGetProcessingStatus() {
    return _GeniusSDKGetProcessingStatus();
  }

  late final _GeniusSDKGetProcessingStatusPtr =
      _lookup<ffi.NativeFunction<GeniusProcessingStatus_t Function()>>(
          'GeniusSDKGetProcessingStatus');
  late final _GeniusSDKGetProcessingStatus =
      _GeniusSDKGetProcessingStatusPtr.asFunction<int Function()>();
}

typedef int_least8_t = ffi.Int8;
typedef Dartint_least8_t = int;
typedef int_least16_t = ffi.Int16;
typedef Dartint_least16_t = int;
typedef int_least32_t = ffi.Int32;
typedef Dartint_least32_t = int;
typedef int_least64_t = ffi.Int64;
typedef Dartint_least64_t = int;
typedef uint_least8_t = ffi.Uint8;
typedef Dartuint_least8_t = int;
typedef uint_least16_t = ffi.Uint16;
typedef Dartuint_least16_t = int;
typedef uint_least32_t = ffi.Uint32;
typedef Dartuint_least32_t = int;
typedef uint_least64_t = ffi.Uint64;
typedef Dartuint_least64_t = int;
typedef int_fast8_t = ffi.Int8;
typedef Dartint_fast8_t = int;
typedef int_fast16_t = ffi.Int16;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Int32;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.Int64;
typedef Dartint_fast64_t = int;
typedef uint_fast8_t = ffi.Uint8;
typedef Dartuint_fast8_t = int;
typedef uint_fast16_t = ffi.Uint16;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.Uint32;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.Uint64;
typedef Dartuint_fast64_t = int;
typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __int64_t = ffi.LongLong;
typedef Dart__int64_t = int;
typedef __uint64_t = ffi.UnsignedLongLong;
typedef Dart__uint64_t = int;
typedef __darwin_intptr_t = ffi.Long;
typedef Dart__darwin_intptr_t = int;
typedef __darwin_natural_t = ffi.UnsignedInt;
typedef Dart__darwin_natural_t = int;
typedef __darwin_ct_rune_t = ffi.Int;
typedef Dart__darwin_ct_rune_t = int;

final class __mbstate_t extends ffi.Union {
  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> __mbstate8;

  @ffi.LongLong()
  external int _mbstateL;
}

typedef __darwin_mbstate_t = __mbstate_t;
typedef __darwin_ptrdiff_t = ffi.Long;
typedef Dart__darwin_ptrdiff_t = int;
typedef __darwin_size_t = ffi.UnsignedLong;
typedef Dart__darwin_size_t = int;
typedef __builtin_va_list = ffi.Pointer<ffi.Char>;
typedef __darwin_va_list = __builtin_va_list;
typedef __darwin_wchar_t = ffi.Int;
typedef Dart__darwin_wchar_t = int;
typedef __darwin_rune_t = __darwin_wchar_t;
typedef __darwin_wint_t = ffi.Int;
typedef Dart__darwin_wint_t = int;
typedef __darwin_clock_t = ffi.UnsignedLong;
typedef Dart__darwin_clock_t = int;
typedef __darwin_socklen_t = __uint32_t;
typedef __darwin_ssize_t = ffi.Long;
typedef Dart__darwin_ssize_t = int;
typedef __darwin_time_t = ffi.Long;
typedef Dart__darwin_time_t = int;
typedef __darwin_blkcnt_t = __int64_t;
typedef __darwin_blksize_t = __int32_t;
typedef __darwin_dev_t = __int32_t;
typedef __darwin_fsblkcnt_t = ffi.UnsignedInt;
typedef Dart__darwin_fsblkcnt_t = int;
typedef __darwin_fsfilcnt_t = ffi.UnsignedInt;
typedef Dart__darwin_fsfilcnt_t = int;
typedef __darwin_gid_t = __uint32_t;
typedef __darwin_id_t = __uint32_t;
typedef __darwin_ino64_t = __uint64_t;
typedef __darwin_ino_t = __darwin_ino64_t;
typedef __darwin_mach_port_name_t = __darwin_natural_t;
typedef __darwin_mach_port_t = __darwin_mach_port_name_t;
typedef __darwin_mode_t = __uint16_t;
typedef __darwin_off_t = __int64_t;
typedef __darwin_pid_t = __int32_t;
typedef __darwin_sigset_t = __uint32_t;
typedef __darwin_suseconds_t = __int32_t;
typedef __darwin_uid_t = __uint32_t;
typedef __darwin_useconds_t = __uint32_t;

final class __darwin_pthread_handler_rec extends ffi.Struct {
  external ffi
      .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
      __routine;

  external ffi.Pointer<ffi.Void> __arg;

  external ffi.Pointer<__darwin_pthread_handler_rec> __next;
}

final class _opaque_pthread_attr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_cond_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_condattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_mutex_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_mutexattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_once_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_rwlock_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([192])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_rwlockattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  external ffi.Pointer<__darwin_pthread_handler_rec> __cleanup_stack;

  @ffi.Array.multi([8176])
  external ffi.Array<ffi.Char> __opaque;
}

typedef __darwin_pthread_attr_t = _opaque_pthread_attr_t;
typedef __darwin_pthread_cond_t = _opaque_pthread_cond_t;
typedef __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
typedef __darwin_pthread_key_t = ffi.UnsignedLong;
typedef Dart__darwin_pthread_key_t = int;
typedef __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
typedef __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
typedef __darwin_pthread_once_t = _opaque_pthread_once_t;
typedef __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
typedef __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
typedef __darwin_pthread_t = ffi.Pointer<_opaque_pthread_t>;
typedef intmax_t = ffi.Long;
typedef Dartintmax_t = int;
typedef uintmax_t = ffi.UnsignedLong;
typedef Dartuintmax_t = int;

final class GeniusArray extends ffi.Struct {
  @ffi.Uint64()
  external int size;

  external ffi.Pointer<ffi.Uint8> ptr;
}

final class GeniusMatrix extends ffi.Struct {
  @ffi.Uint64()
  external int size;

  external ffi.Pointer<GeniusArray> ptr;
}

final class GeniusAddress extends ffi.Struct {
  /// A string prepended with `0x` followed by 64 hex characters,
  /// including a null-terminating char just for safety.
  @ffi.Array.multi([67])
  external ffi.Array<ffi.Char> address;
}

/// @brief Represents a Genius token value in fixed-point format as a string.
///
/// This structure provides enough space to hold the largest possible Genius token
/// string value ("18446744073709.551615") plus the null terminator.
final class GeniusTokenValue extends ffi.Struct {
  /// < String representation of the Genius token value
  @ffi.Array.multi([22])
  external ffi.Array<ffi.Char> value;
}

/// @brief A binary identifier for a Genius-compatible token.
final class GeniusTokenID extends ffi.Struct {
  /// < 32-byte raw token ID used internally
  @ffi.Array.multi([32])
  external ffi.Array<ffi.UnsignedChar> data;
}

typedef PayAmount_t = ffi.Uint64;
typedef DartPayAmount_t = int;
typedef GeniusNodeReturnValue_t = ffi.Int32;
typedef DartGeniusNodeReturnValue_t = int;
typedef GeniusNodeState_t = ffi.Int32;
typedef DartGeniusNodeState_t = int;
typedef GeniusTransactionManagerState_t = ffi.Int32;
typedef DartGeniusTransactionManagerState_t = int;
typedef GeniusTransactionStatus_t = ffi.Int32;
typedef DartGeniusTransactionStatus_t = int;
typedef GeniusProcessingStatus_t = ffi.Int32;
typedef DartGeniusProcessingStatus_t = int;

enum GeniusNodeReturnValue {
  GENIUS_NODE_RET_OK(0),
  GENIUS_NODE_ERROR_NOT_INITIALIZED(1),
  GENIUS_NODE_ERROR_PROCESS_IMAGE(2),
  GENIUS_NODE_ERROR_MINT(3),
  GENIUS_NODE_INVALID_ARGUMENT(4),
  GENIUS_NODE_ERROR_TRANSFER(5),
  GENIUS_NODE_ERROR_PAY_DEV(6);

  final int value;
  const GeniusNodeReturnValue(this.value);

  static GeniusNodeReturnValue fromValue(int value) => switch (value) {
        0 => GENIUS_NODE_RET_OK,
        1 => GENIUS_NODE_ERROR_NOT_INITIALIZED,
        2 => GENIUS_NODE_ERROR_PROCESS_IMAGE,
        3 => GENIUS_NODE_ERROR_MINT,
        4 => GENIUS_NODE_INVALID_ARGUMENT,
        5 => GENIUS_NODE_ERROR_TRANSFER,
        6 => GENIUS_NODE_ERROR_PAY_DEV,
        _ => throw ArgumentError(
            'Unknown value for GeniusNodeReturnValue: $value'),
      };
}

/// @brief Node state enumeration (maps to GeniusNode::NodeState)
/// Values must match GeniusNode::NodeState enum values
enum GeniusNodeState {
  GENIUS_NODE_CREATING(0),
  GENIUS_NODE_MIGRATING_DATABASE(1),
  GENIUS_NODE_INITIALIZING_DATABASE(2),
  GENIUS_NODE_INITIALIZING_PROCESSING(3),
  GENIUS_NODE_INITIALIZING_BLOCKCHAIN(4),
  GENIUS_NODE_INITIALIZING_TRANSACTIONS(5),
  GENIUS_NODE_INITIALIZING_DHT(6),
  GENIUS_NODE_READY(7);

  final int value;
  const GeniusNodeState(this.value);

  static GeniusNodeState fromValue(int value) => switch (value) {
        0 => GENIUS_NODE_CREATING,
        1 => GENIUS_NODE_MIGRATING_DATABASE,
        2 => GENIUS_NODE_INITIALIZING_DATABASE,
        3 => GENIUS_NODE_INITIALIZING_PROCESSING,
        4 => GENIUS_NODE_INITIALIZING_BLOCKCHAIN,
        5 => GENIUS_NODE_INITIALIZING_TRANSACTIONS,
        6 => GENIUS_NODE_INITIALIZING_DHT,
        7 => GENIUS_NODE_READY,
        _ => throw ArgumentError('Unknown value for GeniusNodeState: $value'),
      };
}

enum GeniusTransactionManagerState {
  /// < Creating the object
  GENIUS_TM_STATE_CREATING(0),

  /// < Initializing the object
  GENIUS_TM_STATE_INITIALIZING(1),

  /// < Synching the transactions
  GENIUS_TM_STATE_SYNCHING(2),

  /// < Ready to process transactions
  GENIUS_TM_STATE_READY(3);

  final int value;
  const GeniusTransactionManagerState(this.value);

  static GeniusTransactionManagerState fromValue(int value) => switch (value) {
        0 => GENIUS_TM_STATE_CREATING,
        1 => GENIUS_TM_STATE_INITIALIZING,
        2 => GENIUS_TM_STATE_SYNCHING,
        3 => GENIUS_TM_STATE_READY,
        _ => throw ArgumentError(
            'Unknown value for GeniusTransactionManagerState: $value'),
      };
}

/// @brief Transaction Status enumeration (maps to TransactionManager::TransactionStatus)
/// Values must match TransactionManager::TransactionStatus enum values
enum GeniusTransactionStatus {
  /// < Transaction created but not yet sent
  GENIUS_TX_STATUS_CREATED(0),

  /// < Transaction is being sent
  GENIUS_TX_STATUS_SENDING(1),

  /// < Transaction confirmed
  GENIUS_TX_STATUS_CONFIRMED(2),

  /// < Transaction being verified
  GENIUS_TX_STATUS_VERIFYING(3),

  /// < Transaction failed
  GENIUS_TX_STATUS_FAILED(4),

  /// < Invalid transaction
  GENIUS_TX_STATUS_INVALID(5);

  final int value;
  const GeniusTransactionStatus(this.value);

  static GeniusTransactionStatus fromValue(int value) => switch (value) {
        0 => GENIUS_TX_STATUS_CREATED,
        1 => GENIUS_TX_STATUS_SENDING,
        2 => GENIUS_TX_STATUS_CONFIRMED,
        3 => GENIUS_TX_STATUS_VERIFYING,
        4 => GENIUS_TX_STATUS_FAILED,
        5 => GENIUS_TX_STATUS_INVALID,
        _ => throw ArgumentError(
            'Unknown value for GeniusTransactionStatus: $value'),
      };
}

enum GeniusProcessingStatus {
  /// < Processing was disabled
  GENIUS_PR_STATUS_DISABLED(0),

  /// < Not processing at the moment
  GENIUS_PR_STATUS_IDLE(1),

  /// < Currently processing a job s
  GENIUS_PR_STATUS_PROCESSING(2);

  final int value;
  const GeniusProcessingStatus(this.value);

  static GeniusProcessingStatus fromValue(int value) => switch (value) {
        0 => GENIUS_PR_STATUS_DISABLED,
        1 => GENIUS_PR_STATUS_IDLE,
        2 => GENIUS_PR_STATUS_PROCESSING,
        _ => throw ArgumentError(
            'Unknown value for GeniusProcessingStatus: $value'),
      };
}

const int __WORDSIZE = 64;

const int __has_safe_buffers = 1;

const int __DARWIN_ONLY_64_BIT_INO_T = 1;

const int __DARWIN_ONLY_UNIX_CONFORMANCE = 1;

const int __DARWIN_ONLY_VERS_1050 = 1;

const int __DARWIN_UNIX03 = 1;

const int __DARWIN_64_BIT_INO_T = 1;

const int __DARWIN_VERS_1050 = 1;

const int __DARWIN_NON_CANCELABLE = 0;

const String __DARWIN_SUF_EXTSN = '\$DARWIN_EXTSN';

const int __DARWIN_C_ANSI = 4096;

const int __DARWIN_C_FULL = 900000;

const int __DARWIN_C_LEVEL = 900000;

const int __STDC_WANT_LIB_EXT1__ = 1;

const int __DARWIN_NO_LONG_LONG = 0;

const int _DARWIN_FEATURE_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_VERS_1050 = 1;

const int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = 1;

const int _DARWIN_FEATURE_UNIX_CONFORMANCE = 3;

const int __has_ptrcheck = 0;

const int __DARWIN_NULL = 0;

const int __PTHREAD_SIZE__ = 8176;

const int __PTHREAD_ATTR_SIZE__ = 56;

const int __PTHREAD_MUTEXATTR_SIZE__ = 8;

const int __PTHREAD_MUTEX_SIZE__ = 56;

const int __PTHREAD_CONDATTR_SIZE__ = 8;

const int __PTHREAD_COND_SIZE__ = 40;

const int __PTHREAD_ONCE_SIZE__ = 8;

const int __PTHREAD_RWLOCK_SIZE__ = 192;

const int __PTHREAD_RWLOCKATTR_SIZE__ = 16;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -32768;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 32767;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 65535;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MAX = 9223372036854775807;

const int INTPTR_MIN = -9223372036854775808;

const int UINTPTR_MAX = -1;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int RSIZE_MAX = 9223372036854775807;

const int WCHAR_MAX = 2147483647;

const int WCHAR_MIN = -2147483648;

const int WINT_MIN = -2147483648;

const int WINT_MAX = 2147483647;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int __bool_true_false_are_defined = 1;

const int true$ = 1;

const int false$ = 0;
