// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:genius_wallet/hive/models/coin_gecko_coin.dart';
import 'package:genius_wallet/hive/models/coin_gecko_market_data.dart';
import 'package:genius_wallet/hive/models/historical_price_cache_entry.dart';
import 'package:genius_wallet/hive/models/news_article.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CoinGeckoCoinAdapter());
    registerAdapter(CoinGeckoMarketDataAdapter());
    registerAdapter(HistoricalPriceCacheEntryAdapter());
    registerAdapter(NewsArticleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CoinGeckoCoinAdapter());
    registerAdapter(CoinGeckoMarketDataAdapter());
    registerAdapter(HistoricalPriceCacheEntryAdapter());
    registerAdapter(NewsArticleAdapter());
  }
}
