name: wallet_storage_template
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  # TODO: Ideally this package would not depend on Flutter.
  # To fix, we could create an abstract `genius_api` that does not depend on Flutter and have a concrete
  # `genius_api` that does, to keep all abstract classes dart-only
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
    version: ^0.0.0
  genius_api:
    path: "../genius_api"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
