// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:genius_api/models/transaction.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionDirectionAdapter());
    registerAdapter(TransactionStatusAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(TransferRecipientsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionDirectionAdapter());
    registerAdapter(TransactionStatusAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(TransferRecipientsAdapter());
  }
}
